_target_: src.models.tokenizer.Tokenizer

vocab_size: 32000 # change to llm vocab dim
embed_dim: 2048  # change this to whatever the embedding dimension is in your pretrained llm 2048 for llama. 2560 for stablelm
encoder:
  _target_: src.models.tokenizer.Encoder
  config:
    _target_: src.models.tokenizer.EncoderDecoderConfig
    resolution: 64
    in_channels: 3
    z_channels: 32000
    ch: 64
    ch_mult: [1, 1, 1, 1, 1]
    num_res_blocks: 2
    attn_resolutions: [8, 16]
    out_ch: 3
    dropout: 0.0
decoder:
  _target_: src.models.tokenizer.Decoder
  config: ${..encoder.config}
