_target_: src.models.tokenizer.Tokenizer

vocab_size: ${..world_model.vocab_size}
embed_dim: ${..world_model.embed_dim}
encoder:
  _target_: src.models.tokenizer.Encoder
  config:
    _target_: src.models.tokenizer.EncoderDecoderConfig
    resolution: 64
    in_channels: 3
    z_channels: ${...vocab_size}
    ch: 64
    ch_mult: [1, 1, 1, 1, 1]
    num_res_blocks: 2
    attn_resolutions: [8, 16]
    out_ch: 3
    dropout: 0.0
decoder:
  _target_: src.models.tokenizer.Decoder
  config: ${..encoder.config}
